project_id = "mornsczwzuksamxmtmbe"

[functions.search-flights]
verify_jwt = true

[functions.search-airports]
verify_jwt = true

[functions.confirm-flight-price]
verify_jwt = true

[functions.create-flight-order]
verify_jwt = true