project_id = "mornsczwzuksamxmtmbe"

[functions.search-flights]
verify_jwt = false

[functions.search-airports]
verify_jwt = false

[functions.get-destinations]
verify_jwt = false

[functions.get-airports]
verify_jwt = false

[functions.get-closest-airport]
verify_jwt = false

[functions.sync-airports]
verify_jwt = false